.TH STR_TO_UPPER 3 "September 2026" "libmyutils" "Library Functions Manual"
.SH NAME
str_to_upper \- convert a string to uppercase in place
.SH SYNOPSIS
.nf
.B #include "mystrfunctions.h"
.sp
.BI "void str_to_upper(char *" str );
.fi
.SH DESCRIPTION
The
.B str_to_upper()
function converts every character in
.I str
to uppercase, in place.
.SH RETURN VALUE
This function does not return a value.
.SH EXAMPLE
.nf
char str[] = "hello";
str_to_upper(str);
/* str is now "HELLO" */
.fi
.SH AUTHOR
Haseeb
.SH SEE ALSO
.BR str_to_lower (3)
